---
- name: "Apply patches to Linux servers"
  hosts: all
  serial: 2
  tasks:
    - name: "Check if application process is running"
      shell: pgrep -x <application_name> && echo "process is running" || echo "Process is not running."
      register: application_process_check
      changed_when: false

    - name: "Stop play if application is running"
      fail: 
        msg: "{{ inventory_hostname }} has a running application. Please stop the application and then proceed with patching."
      when: application_process_check.stdout == "process is running"

    - name: "Apply patches to the server"
      yum:
        name: kernel
        state: latest
      when: 
        - application_process_check.stdout == "Process is not running."
        - ansible_distribution in ["CentOS", "RedHat"]
      register: patch_update

    - name: "Check if reboot is required"
      shell: |
        KERNEL_NEW=$(rpm -q --last kernel | head -1 | awk '{print $1}' | sed 's/kernel-//')
        KERNEL_NOW=$(uname -r)
        if [[ "$KERNEL_NEW" != "$KERNEL_NOW" ]]; then
          echo "reboot needed"
        else
          echo "reboot not needed"
        fi
      register: reboot_status
      ignore_errors: true

    - name: "Reboot the system if needed"
      command: shutdown -r +1 "Rebooting system after patching"
      async: 0
      poll: 0
      when: reboot_status.stdout == "reboot needed"
      register: reboot_started
      ignore_errors: true

    - name: "Wait 1 minute for the system to come up"
      pause:
        minutes: 1

    - name: "Check if the system is back online"
      local_action:
        module: shell
        args:
          cmd: ansible -u {{ ansible_user }} -m ping {{ inventory_hostname }}
      register: result
      until: result.rc == 0
      retries: 30
      delay: 10

    - name: "Verify system uptime"
      shell: uptime
      register: uptime_result
      changed_when: false
