---
- name: "Apply patches to Amazon Linux servers"
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  vars:
    ansible_become_password: "root"  # Recommended to use Ansible Vault for this
  serial: 2
  tasks:
    - name: "Ensure httpd is installed"
      dnf:
        name: httpd
        state: present
      register: httpd_installed

    - name: "Check if application process is running"
      shell: "pgrep -x httpd && echo 'process is running' || echo 'Process is not running.'"
      register: application_process_check
      changed_when: false

    - name: "Stop play if application is running"
      fail:
        msg: "{{ inventory_hostname }} has a running application. Please stop the application and then proceed with patching."
      when: application_process_check.stdout == "process is running"

    - name: "Apply patches to the server"
      dnf:
        name: kernel
        state: latest
      when:
        - application_process_check.stdout == "Process is not running."
        - ansible_distribution in ["CentOS", "RedHat", "Amazon"]
      register: patch_update

    - name: "Check if reboot is required"
      shell: |
        KERNEL_NEW=$(rpm -q --last kernel | head -1 | awk '{print $1}' | sed 's/kernel-//')
        KERNEL_NOW=$(uname -r)
        if [[ "$KERNEL_NEW" != "$KERNEL_NOW" ]]; then
          echo "reboot needed"
        else
          echo "reboot not needed"
        fi
      register: reboot_status
      ignore_errors: true

    - name: "Reboot the system if needed"
      reboot:
        msg: "Rebooting system after patching"
        reboot_timeout: 300
      when: reboot_status.stdout == "reboot needed"

    - name: "Verify system uptime"
      shell: uptime
      register: uptime_result
      changed_when: false
